@startuml

package Application {
class CreateOrderCommand
class CreateOrderHandler
class OutboxPublisher
class IntegrationEventMapper
interface OrderRepository
interface OutboxRepository
interface MessageBrokerPort
}

package Domain {
class Order
class OrderItem
abstract class DomainEvent
class OrderCreatedDomainEvent
abstract class Delivery
class PickupDelivery
class AddressDelivery

abstract class Payment
class CardPayment
class CreditPayment
}

package Infrastructure {
class SqlOrderRepository
class SqlOutboxRepository
class MessageBrokerClient
class IntegrationEvent
class OrderCreatedIntegrationEvent
}

package Interface {
class HttpController
}

HttpController --> CreateOrderCommand
CreateOrderCommand --> CreateOrderHandler

CreateOrderHandler --> Order
CreateOrderHandler --> IntegrationEventMapper

CreateOrderHandler --> OrderRepository
CreateOrderHandler --> OutboxRepository

Order *-- OrderItem
Order *-- Delivery
Order *-- Payment
Order --> DomainEvent : records
Order --> OrderCreatedDomainEvent
DomainEvent <|-- OrderCreatedDomainEvent
CreateOrderHandler --> Order : pullDomainEvents()
IntegrationEventMapper --> DomainEvent
IntegrationEventMapper --> IntegrationEvent
IntegrationEvent <|-- OrderCreatedIntegrationEvent

Delivery <|-- PickupDelivery
Delivery <|-- AddressDelivery

Payment <|-- CardPayment
Payment <|-- CreditPayment

OutboxPublisher --> OutboxRepository
OutboxPublisher --> MessageBrokerPort
OutboxPublisher --> IntegrationEvent
SqlOrderRepository ..|> OrderRepository
SqlOutboxRepository ..|> OutboxRepository
MessageBrokerClient ..|> MessageBrokerPort
MessageBrokerClient --> OrderCreatedIntegrationEvent

@enduml
